# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta1',
            name='pregunta4',
            field=models.CharField(choices=[('a', 'Candidato del Oficialismo'), ('b', 'Candidato de la Oposición'), ('c', 'Candidato Independiente'), ('d', 'No votaría')], default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuesta1',
            name='pregunta3',
            field=models.CharField(choices=[('a', 'Candidato del Oficialismo'), ('b', 'Candidato de la Oposición'), ('c', 'Candidato Independiente'), ('d', 'No votaría')], max_length=1),
        ),
        migrations.AlterField(
            model_name='encuesta1',
            name='telefono',
            field=models.CharField(help_text='Número telefónico de contacto con la persona', max_length=18, validators=[django.core.validators.RegexValidator('^\\(\\+058\\)-\\d{3}-\\d{7}$', "Número telefónico inválido. Solo se permiten números y los símbolos: '(', ')', '-', '+'")]),
        ),
    ]
