# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20170719_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta1',
            name='pregunta4',
            field=models.CharField(choices=[('1', '1.- Jehyson Jose Guzman Araque / Simon Pablo Figueroa'), ('2', '2.- Agustin Alexis Alvarez Tovar / Lorenza Ullan Severino'), ('3', '3.- Betty Carolina PeÑa Lopez'), ('4', '4.- Elias Rafael Sanchez Verde / Juan Carlos Lenzo'), ('5', '5.- Enrique Antonio Plata Ramirez / Teresa De Jesus Mora '), ('6', '6.- Nelsy Carolina Rivera Quinchoa'), ('7', '7.- Luis Carlos Perales Araque'), ('8', '8.- Johnny Rafael Andrade Barreto'), ('9', '9.- Jorge David Sandoval Rujano'), ('10', '10.- Gracian Claret Rondon Dezeo'), ('11', '11.- Greny Rosana Uzcategui Lacruz'), ('12', '12.- Hector Ramon Rojas Pernia'), ('13', '13.- Wilmer Arquimedes Iglesias Pino / Ramon David Fajardo Guanipa'), ('14', '14.- Alirio Jose Liscano '), ('15', '15.- Jose Rafael Luna ')], max_length=2),
        ),
    ]
